import { ClerkProvider, UserButton, auth, currentUser } from '@clerk/nextjs'
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const{userId} = auth();
  // console.log("userId",userId)
  const user = await currentUser(); 
  // console.log("user",user);
  return (
    <ClerkProvider> 
    <html lang="en">
      <body className={inter.className}>
      <div className="header">
        <nav>
          <Link href="/">Home</Link>
          <Link href="/posts">Posts</Link>
          <Link href="/users">Profile</Link>
        </nav>

        <UserButton afterSignOutUrl='/'/>
        </div>
        {children}
        
      </body>
    </html>
    </ClerkProvider>
  );
}
